### PR TITLE
feat: support patch 0.217.22

### LINKED ISSUE #44: Patch 0.217.22
Support newly released patch https://valheim.com/news/patch-0-217-22/

### PR DESCRIPTION
**Pull request by thesharp**
Fixes #44.

Can confirm that multiplayer works.

### CODE REVIEW

**Comment by timkurvers** [comment]
Excellent, thank you! 🥳

**Comment by dadegroot** [comment]
Latest hotfix has broken the build script unfortantely:

Valheim data for build 12314274 not found, exiting..
(the build script may need to be updated if a patch was recently released)

**Comment by thesharp** [comment]
@dadegroot Latest hotfix hasn't broken anything. The PR for the newly released version has been there for some days now: https://github.com/timkurvers/valheim-macos/pull/46. It's up to @timkurvers to merge it.

**Comment by dadegroot** [comment]
Oh cool :)

I had a play, changing the build version in the script, which built fine, but the result crashes after the splash screen. (Sonoma retail 14.0 on M2 Max) I'll wait 'til the new merge.

**Comment by timkurvers** [comment]
Apologies folks, have been away for the weekend. Hope to merge the open PR soonish 🥳

**Comment by zoofood** [comment]
No worries Tim! This is open source, we're just happy for the project, and appreciate your efforts here.

**Comment by timkurvers** [comment]
Have documented the build script failure as a known issue in the README: 39270c14bb9ce6f6f338c877027023aedebbdaf8.

Thanks for commenting, wouldn't have figured that out otherwise 👍

**Pull request merged**
