### PR TITLE
fix: build and bundle DiskSpacePlugin to allow saving once more

### LINKED ISSUE #73: Save/Autosave not working with build 0.217.38
First, thanks for your effort porting Valheim to Mac OS.

I patched the build 0.217.38 yesterday and found out, that the progress isn't getting saved.
Neither auto-save nor manual save seems to work.

### PR DESCRIPTION
**Pull request by timkurvers**
Fixes #73 by building and bundling `DiskSpacePlugin.dylib`, a macOS variant of the library introduced in a recent Valheim patch:

Screenshot 2023-12-29 at 00 21 30

Will keep this PR open for others to verify this actually works. In particular, not entirely sure if every Mac ships with `cc` available by default (or whether that requires installing Xcode).

---

To try this variant of the build script:

```sh
git pull # or `git fetch` may suffice
git checkout fix/diskspaceplugin
./build.sh
```

If you'd like to swap back to the stable variant, `git checkout main` again.

### CODE REVIEW

**Comment by alandtse** [comment]
Confirmed manual saves worked for me on a 2020 Macbook Pro M1. Didn't play to an autosave but checked against a prepatch build.

Not sure if it was related but in the prepatch version, hitting logout would hang my Macbook. With the patch, it doesn't hang.

**Review by alandtse — APPROVED** [review]

**Comment by kvia-cadabra** [comment]
Hi all. I have a MacBook Pro 16 Apple M1 Max. MacOS Ventura 13.4.1. Thx for the path. It's work. I'm happy. Have a good day.

**Comment by timkurvers** [comment]
Thanks for testing! 👍 Make sure to swap back to `main`.

**Comment by Dissplinth** [comment]
Hello, I really appreciate the work you're doing on this! 
Do you mind explaining how to apply this patch? I'm pretty unfamiliar with using Terminal.

**Comment by timkurvers** [comment]
> Hello, I really appreciate the work you're doing on this! Do you mind explaining how to apply this patch? I'm pretty unfamiliar with using Terminal.

This particular fix has already been merged and is included in the latest build script. Following the instructions under [patching](https://github.com/timkurvers/valheim-macos#patching) in the README should work and result in an updated build with the DiskSpacePlugin included.

**Comment by Dissplinth** [comment]
Thanks for the response. Patching it didn't seem to work for me, either on a Local or cloud server. It seems like other people are having success though, not sure what my issue is. If there's anything else you can think of that I might be forgetting, I'd love to figure it out. If not, I'll just appreciate that I can play on my friends servers on Mac finally.

**Comment by timkurvers** [comment]
> Thanks for the response. Patching it didn't seem to work for me, either on a Local or cloud server. It seems like other people are having success though, not sure what my issue is. If there's anything else you can think of that I might be forgetting, I'd love to figure it out. If not, I'll just appreciate that I can play on my friends servers on Mac finally.

Could you try the following:

1) Navigate to the folder where you normally run `./build.sh` in a terminal
2) Run `ls -la build/Valheim.app/Contents/PlugIns`
3) Verify that the output includes `DiskSpacePlugin.dylib`

It may also be useful to have a look at the `~/Library/Logs/IronGate/Valheim/Player.log` file, when you try to save and see if any error messages pop up.

**Comment by Dissplinth** [comment]
Yup, it's there. I can also see the DiskSpacePlugin folder in Finder.
However, I don't have either the  ~/Library/Logs/IronGate folder or the ~/Library/Application Support/unity.IronGate.Valheim-macOS-Custom/characters_local file.
image
image

**Comment by timkurvers** [comment]
Thanks for checking, that `dylib`-file should be correct 👍

Just to rule out the following:

- The `Library` folder in the home folder is hidden by default: press `cmd + shift + .` (dot) to reveal hidden files.

- There seem to be multiple `valheim-macos` folders in the screenshot, could you double check that you are running `Valheim.app` that contains the `DiskSpacePlugin.dylib` file?

**Comment by Dissplinth** [comment]
Thank you so much, that was the answer: I must have been running that second Valheim app that was nested inside the other folder. Deleting that and running the other app directly from Finder made everything work fine and the world is saving without issue.
Greatly appreciate your responses, and everything you're doing for this project!

**Pull request merged**
